"""Standard-library-only domain core for the NOEMA mail gateway."""

from .contracts import (
    FORBIDDEN_FIELDS,
    REQUEST_TYPES,
    RESPONSE_TYPES,
    ContractValidationError,
    ErrorCode,
    MailAddAttachmentRequest,
    MailAddAttachmentResponse,
    MailCreateDraftRequest,
    MailCreateDraftResponse,
    MailGetDraftSummaryRequest,
    MailGetDraftSummaryResponse,
    MailGetThreadRequest,
    MailGetThreadResponse,
    MailReadRequest,
    MailReadResponse,
    MailSearchRequest,
    MailSearchResponse,
    MailUpdateDraftRequest,
    MailUpdateDraftResponse,
    validate_request,
)
from .exceptions import (
    CredentialError,
    InvalidTransitionError,
    MailCoreError,
    RuntimeSecurityError,
    StagingSecurityError,
    ValidationError,
)
from .hashing import content_hash
from .models import (
    MAX_ATTACHMENT_SIZE,
    MAX_BODY_TEXT_SIZE,
    MAX_RECIPIENTS,
    AttachmentRef,
    CaseContext,
    Draft,
    EmailAddress,
)
from .redaction import redact
from .secrets import SecretValue
from .status import DraftStatus, transition
from .untrusted import UntrustedText, mark_untrusted, strip_control_chars

__all__ = [
    "FORBIDDEN_FIELDS",
    "MAX_ATTACHMENT_SIZE",
    "MAX_BODY_TEXT_SIZE",
    "MAX_RECIPIENTS",
    "REQUEST_TYPES",
    "RESPONSE_TYPES",
    "AttachmentRef",
    "CaseContext",
    "ContractValidationError",
    "CredentialError",
    "Draft",
    "DraftStatus",
    "EmailAddress",
    "ErrorCode",
    "InvalidTransitionError",
    "MailAddAttachmentRequest",
    "MailAddAttachmentResponse",
    "MailCoreError",
    "MailCreateDraftRequest",
    "MailCreateDraftResponse",
    "MailGetDraftSummaryRequest",
    "MailGetDraftSummaryResponse",
    "MailGetThreadRequest",
    "MailGetThreadResponse",
    "MailReadRequest",
    "MailReadResponse",
    "MailSearchRequest",
    "MailSearchResponse",
    "MailUpdateDraftRequest",
    "MailUpdateDraftResponse",
    "RuntimeSecurityError",
    "SecretValue",
    "StagingSecurityError",
    "UntrustedText",
    "ValidationError",
    "content_hash",
    "redact",
    "mark_untrusted",
    "strip_control_chars",
    "transition",
    "validate_request",
]
